#!/usr/bin/env python
import copy
import sys

from chimera.cli.cli import ChimeraCLI, action


class ChimeraAutoSkyFlat(ChimeraCLI):
    def __init__(self):
        ChimeraCLI.__init__(self, "chimera-skyflat", "SkyFlats", 0.1)
        self.add_help_group("SKYFLAT", "skyFlats")
        self.add_controller(name="skyflat",
                           cls="AutoSkyFlat",
                           required=True,
                           help_group="SKYFLAT",
                           help="Auto Sky Flats")
        self.add_parameters(
            dict(name="sun_alt_hi", long="sun-high", type="float", help_group="SKYFLAT", help="Highest Sun altitude",
                 metavar="FILE"),
            dict(name="sun_alt_low", long="sun-low", type="float", help_group="SKYFLAT", help="Lowest Sun altitude",
                 metavar="FILE"),
            dict(name='filter', long='filter', short='f', required=True, type='string', help_group='SKYFLAT', help='Skyflat filter name'),
            dict(name='number', long='number', short='n', type='int', help_group='SKYFLAT', help='Number of skyflats to take on the filter'),
            dict(name="binning", default="1x1", help="Apply the selected binning to all frames", help_group="SKYFLAT")
        )

    @action(long="auto", help="Does a sequence of sky flats", help_group="SKYFLAT")
    def do_sequence(self, options):
        """
        Sets variables using command line options
        Take skyflats according to options
        """
        self.out("Pointing scope to the zenith and waiting for the Sun to reach skyflats altitude range")
        if options.sun_alt_low > options.sun_alt_hi:
            self.exit("sunHi needs to be less than sunLow")
        if options.sun_alt_hi:
            self.skyflat["sun_alt_hi"] = options.sun_alt_hi
        if options.sun_alt_low:
            self.skyflat["sun_alt_low"] = options.sun_alt_low
        if options.number:
            num = options.number
        else:
            num = None

        def expose_complete(filter_id, i_flat, exptime, counts):
            self.out('Filter: %s, Skyflat # %i - Exposure time: %3.2f seconds - Counts: %3.2f' % (filter_id, i_flat, exptime, counts))

        self.skyflat.expose_complete += expose_completete

        request = {"binning": options.binning}
        for filter_id in options.filter.split(','):
            self.skyflat.get_flats(filter_id, n_flats=num, request=request)
        self.out("Finished.")

        self.skyflat.expose_complete -= expose_complete

        # @callback(self.localManager)
        # def exposeBegin(request):
        #     self.out('Taking %i flats on filter %s' % (num, filter_id))




    def __abort__(self):
        self.out("\naborting... ", endl="")

        # copy self.skyflat Proxy because we are running from a differente
        # thread (yes, Pyro is tricky!)
        skyflat = copy.copy(self.skyflat)
        skyflat.abort()


def main():
    cli = ChimeraAutoSkyFlat()
    cli.run(sys.argv)
    cli.wait()


if __name__ == '__main__':
    main()
